//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CophiPoint {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GeneralResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GeneralResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CophiPoint.GeneralResources", typeof(GeneralResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AlertAdd {
            get {
                return ResourceManager.GetString("AlertAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AlertCancel {
            get {
                return ResourceManager.GetString("AlertCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string HistoryAccountTitle {
            get {
                return ResourceManager.GetString("HistoryAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase history.
        /// </summary>
        public static string HistoryTitle {
            get {
                return ResourceManager.GetString("HistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        public static string InfoTitle {
            get {
                return ResourceManager.GetString("InfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string LoginFailedAlert {
            get {
                return ResourceManager.GetString("LoginFailedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogOutBtn {
            get {
                return ResourceManager.GetString("LogOutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported media type.
        /// </summary>
        public static string MediaTypeError {
            get {
                return ResourceManager.GetString("MediaTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with MojeID.
        /// </summary>
        public static string MojeIdBtn {
            get {
                return ResourceManager.GetString("MojeIdBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More about CophiPoint.
        /// </summary>
        public static string MoreAboutBtn {
            get {
                return ResourceManager.GetString("MoreAboutBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No purchases found.
        /// </summary>
        public static string NoHistoryTxt {
            get {
                return ResourceManager.GetString("NoHistoryTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you realy want add {0} ({1}) to your purchuases?.
        /// </summary>
        public static string OrderConfirmAlertMsg {
            get {
                return ResourceManager.GetString("OrderConfirmAlertMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm order.
        /// </summary>
        public static string OrderConfirmAlertTitle {
            get {
                return ResourceManager.GetString("OrderConfirmAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process order due to product conflict. Please try again..
        /// </summary>
        public static string OrderFailedMsg {
            get {
                return ResourceManager.GetString("OrderFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product error.
        /// </summary>
        public static string OrderFailedTitle {
            get {
                return ResourceManager.GetString("OrderFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to pay.
        /// </summary>
        public static string PayInfoBtn {
            get {
                return ResourceManager.GetString("PayInfoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payments.
        /// </summary>
        public static string PayInfoTitle {
            get {
                return ResourceManager.GetString("PayInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product price has chaged. Do you want to add {0} ({1}) with new price {2}..
        /// </summary>
        public static string ProductPriceChangedAlert {
            get {
                return ResourceManager.GetString("ProductPriceChangedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while requesting server. Please try again later..
        /// </summary>
        public static string ServerErrorMsg {
            get {
                return ResourceManager.GetString("ServerErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comunnication error.
        /// </summary>
        public static string ServerErrorTitle {
            get {
                return ResourceManager.GetString("ServerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected HTTP response code.
        /// </summary>
        public static string StatusCodeError {
            get {
                return ResourceManager.GetString("StatusCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CophiPoint provides refreshemnt (at this point coffee only) for MFF attendees..
        /// </summary>
        public static string WelcomeAbout {
            get {
                return ResourceManager.GetString("WelcomeAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is intended for MFF attendees only and should be used according to internal policy..
        /// </summary>
        public static string WelcomeBasic {
            get {
                return ResourceManager.GetString("WelcomeBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to MFF Cophi-Point.
        /// </summary>
        public static string WelcomeHeader {
            get {
                return ResourceManager.GetString("WelcomeHeader", resourceCulture);
            }
        }
    }
}
