name: CD

on:
  push:
    branches: 
      - 'master'
  pull_request:
    branches: 
      - 'master'

jobs:
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup variables
      uses: datamonsters/replace-action@v2
      with:
        files: CophiPoint/Config.cs
        replacements: '$CONFIG_URL=${{ secrets.CONFIG_URL }}'
    - name: Setup variables
      uses: datamonsters/replace-action@v2
      with:
        files: CophiPoint/Api/AuthConstants.cs
        replacements: '$CLIENT_ID=${{ secrets.CLIENT_ID }},$CLIENT_SECRET=${{ secrets.CLIENT_SECRET }},$CUSTOM_SCHEME=${{ secrets.CUSTOM_SCHEME }}'
    - name: Build APK
      run: |
        msbuild CophiPoint.Android/CophiPoint.Android.csproj /verbosity:normal /restore /t:Package /p:Configuration=Release
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: CophiPoint.Android/bin/Release
        signingKeyBase64: ${{ secrets.APK_KEYSTORE_64 }}
        alias: CophiPoint
        keyStorePassword: ${{ secrets.APK_KEYSTORE_PASS }}
        keyPassword: ${{ secrets.APK_ALIAS_PASS }}
    - name: file list
      run: |
        tree CophiPoint.Android\bin /F
    - name: Upload APK (arm64)
      uses: actions/upload-artifact@v1
      with:
        name: CophiPoint-arm64-v8a.apk
        path: CophiPoint.Android/bin/Release/cz.bubyx.CophiPoint-arm64-v8a.apk
    - name: Upload APK (armeabi)
      uses: actions/upload-artifact@v1
      with:
        name: CophiPoint-armeabi-v7a.apk
        path: CophiPoint.Android/bin/Release/cz.bubyx.CophiPoint-armeabi-v7a.apk
    - name: Upload APK (general)
      uses: actions/upload-artifact@v1
      with:
        name: CophiPoint.apk
        path: CophiPoint.Android/bin/Release/cz.bubyx.CophiPoint.apk
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: CophiPoint
        path: ${{env.SIGNED_RELEASE_FILE}}
  
#  iOS:
#    runs-on: macos-latest
#    steps:
#    - uses: actions/checkout@v1
#    - name: Build
#      run: 
