name: CD

on:
  push:
    branches: 
      - 'master'
  pull_request:
    branches: 
      - 'master'

jobs:
   iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: |
        msbuild CophiPoint.Android/CophiPoint.Android.csproj /verbosity:normal /restore /t:SignAndroidPackage /p:Configuration=Release
