  
name: CD

on:
  push:
    branches: 
      - 'master'
  pull_request:
    branches: 
      - 'master'

jobs:
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup URL
      uses: datamonsters/replace-action@v2
      with:
        files: CophiPoint/Config.cs
        replacements: '$CONFIG_URL=${{ secrets.CONFIG_URL }}'
    - name: Setup OIDC
      uses: datamonsters/replace-action@v2
      with:
        files: CophiPoint/Api/AuthConstants.cs
        replacements: '$CLIENT_ID=${{ secrets.CLIENT_ID }},$CLIENT_SECRET=${{ secrets.CLIENT_SECRET }},$CUSTOM_SCHEME=${{ secrets.CUSTOM_SCHEME }}'
    - name: Setup Manifest
      uses: datamonsters/replace-action@v2
      with:
        files: CophiPoint.Android/Properties/AndroidManifest.xml
        replacements: '$CUSTOM_SCHEME=${{ secrets.CUSTOM_SCHEME }}'
    - name: Build APK
      run: |
        msbuild CophiPoint.Android/CophiPoint.Android.csproj /verbosity:normal /restore /t:SignAndroidPackage /p:Configuration=Release
    - name: file list
      run: ls -R CophiPoint.Android/bin/
    - name: Upload APK (arm64)
      uses: actions/upload-artifact@v1
      with:
        name: CophiPoint-arm64-v8a-Signed.apk
        path: CophiPoint.Android/bin/Release/cz.bubyx.CophiPoint-arm64-v8a-Signed.apk
    - name: Upload APK (armeabi)
      uses: actions/upload-artifact@v1
      with:
        name: CophiPoint-armeabi-v7a-Signed.apk
        path: CophiPoint.Android/bin/Release/cz.bubyx.CophiPoint-armeabi-v7a-Signed.apk
    - name: Upload APK (general)
      uses: actions/upload-artifact@v1
      with:
        name: CophiPoint-Signed.apk
        path: CophiPoint.Android/bin/Release/cz.bubyx.CophiPoint-Signed.apk
  
#  iOS:
#    runs-on: macos-latest
#    steps:
#    - uses: actions/checkout@v1
#    - name: Build
#      run: 
