name: CI

on:
  push:
    branches: 
      - 'master'
  pull_request:
    branches: 
      - 'master'

env:
  boots_version: 1.0.2.421

jobs:
  apk:
    name: Generate Android APK
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache Tooling
      uses: actions/cache@v1
      env:
        cache-name: cache-vs-tooling
      with:
        path: 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\'   
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
          
    - name: Boots intall tooling
      run: |
        dotnet tool install --global boots --version $env:boots_version
        boots --preview XamarinAndroid
      
    - name: Setup NuGet
      uses: warrenbuckley/Setup-Nuget@v1
    - name: Build Xamarin Android
      run: |
        msbuild CophiPoint.Android/CophiPoint.Android.csproj /restore /t:Package /p:Configuration=Release
    - name: List Dir
      run: Tree . /F
    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: CophiPoint.Android/bin/Release
        signingKeyBase64: ${{ secrets.APK_KEYSTORE_64 }}
        alias: ${{ secrets.APK_ALIAS }}
        keyStorePassword: ${{ secrets.APK_KEYSTORE_PASS }}
        keyPassword: ${{ secrets.APK_ALIAS_PASS }}
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: CophiPoint
        path: ${{env.SIGNED_RELEASE_FILE}}
